2024-04-23 01:31:47,250 INFO    MainThread:14808 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-23 01:31:47,250 INFO    MainThread:14808 [wandb_setup.py:_flush():76] Configure stats pid to 14808
2024-04-23 01:31:47,251 INFO    MainThread:14808 [wandb_setup.py:_flush():76] Loading settings from /home/billalmokhtari/.config/wandb/settings
2024-04-23 01:31:47,251 INFO    MainThread:14808 [wandb_setup.py:_flush():76] Loading settings from /home/billalmokhtari/Documents/projects/Image-Clustering-Based-on-Node-Edge-Duality-Message-Passing-Using-Graph-Attention-Networks/wandb/settings
2024-04-23 01:31:47,251 INFO    MainThread:14808 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-23 01:31:47,251 INFO    MainThread:14808 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-23 01:31:47,251 INFO    MainThread:14808 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/billalmokhtari/Documents/projects/Image-Clustering-Based-on-Node-Edge-Duality-Message-Passing-Using-Graph-Attention-Networks/main.py', 'program': '/home/billalmokhtari/Documents/projects/Image-Clustering-Based-on-Node-Edge-Duality-Message-Passing-Using-Graph-Attention-Networks/main.py'}
2024-04-23 01:31:47,251 INFO    MainThread:14808 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-23 01:31:47,252 INFO    MainThread:14808 [wandb_init.py:_log_setup():521] Logging user logs to /home/billalmokhtari/Documents/projects/Image-Clustering-Based-on-Node-Edge-Duality-Message-Passing-Using-Graph-Attention-Networks/wandb/run-20240423_013147-smnozksr/logs/debug.log
2024-04-23 01:31:47,252 INFO    MainThread:14808 [wandb_init.py:_log_setup():522] Logging internal logs to /home/billalmokhtari/Documents/projects/Image-Clustering-Based-on-Node-Edge-Duality-Message-Passing-Using-Graph-Attention-Networks/wandb/run-20240423_013147-smnozksr/logs/debug-internal.log
2024-04-23 01:31:47,252 INFO    MainThread:14808 [wandb_init.py:init():561] calling init triggers
2024-04-23 01:31:47,252 INFO    MainThread:14808 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-23 01:31:47,252 INFO    MainThread:14808 [wandb_init.py:init():611] starting backend
2024-04-23 01:31:47,252 INFO    MainThread:14808 [wandb_init.py:init():615] setting up manager
2024-04-23 01:31:47,259 INFO    MainThread:14808 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-23 01:31:47,263 INFO    MainThread:14808 [wandb_init.py:init():623] backend started and connected
2024-04-23 01:31:47,270 INFO    MainThread:14808 [wandb_init.py:init():715] updated telemetry
2024-04-23 01:31:47,287 INFO    MainThread:14808 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-23 01:31:47,713 ERROR   MainThread:14808 [wandb_init.py:init():774] encountered error: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (smnozksr) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
2024-04-23 01:31:47,874 ERROR   MainThread:14808 [wandb_init.py:init():1199] You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (smnozksr) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
Traceback (most recent call last):
  File "/home/billalmokhtari/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/billalmokhtari/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.UsageError: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (smnozksr) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
2024-04-23 01:31:49,004 WARNING MsgRouterThr:14808 [router.py:message_loop():77] message_loop has been closed
